<script lang="ts">
 import PublicShell from "$public/components/PublicShell.svelte"; import PageHeader from "$public/components/PageHeader.svelte"; import { Badge } from "$lib/components/ui/badge"; import { Card, CardContent } from "$lib/components/ui/card";
  import hero from "@/assets/bbdit-campus-hero.webp"; import library from "@/assets/bbdit-library.jpg"; import convocation from "@/assets/bbdit-convocation.jpg";
  const claims=[{id:"since-2000",tag:"Established",title:"25 years of institution building",text:"Babu Banarsi Das Institute of Technology was established in 2000 under the aegis of Rajiv Educational Trust to provide contemporary, quality education in engineering and management. The institute marked its 25th establishment year with Encore 2026.",image:convocation,alt:"BBDIT graduates celebrating at convocation",source:"Institute overview and Encore 2026 notice"},{id:"campus",tag:"Campus",title:"A 15-acre learning environment",text:"The institute describes a 15-acre green campus on the Delhi–Meerut Road with smart classrooms, equipped laboratories, Wi-Fi access, library and e-library facilities, and residential support.",image:hero,alt:"BBDIT academic campus",source:"Official BBDIT overview"},{id:"recognition",tag:"Recognition",title:"Affiliated and professionally connected",text:"BBDIT is affiliated to Dr. A.P.J. Abdul Kalam Technical University and recognized by AICTE. Pharmacy programmes also reference PCI and the Board of Technical Education, Uttar Pradesh.",image:library,alt:"Students in the BBDIT library",source:"Official affiliations page"}];
</script>

<svelte:head><title>About BBDIT</title></svelte:head>
<PublicShell><main><PageHeader eyebrow="About BBDIT" title="Developing Nation Since 2000" description="The history, learning environment and affiliations behind the claims shown across this website." />
  <section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div class="max-w-3xl"><h2 class="font-heading text-3xl font-semibold">A multicultural learning community</h2><p class="mt-4 leading-7 text-muted-foreground">BBDIT’s stated vision is to build a community founded on academic excellence, preparing students to contribute productively, responsibly and ethically to Indian and global society. Its mission combines technical capability, employability, innovation and professional responsibility.</p></div>
  <div class="mt-14 space-y-16">{#each claims as claim,i}<article id={claim.id} class="grid scroll-mt-24 gap-8 lg:grid-cols-2 lg:items-center"><img src={claim.image} alt={claim.alt} class:lg:order-2={i%2===0} class="aspect-[16/10] w-full rounded-xl object-cover" /><div><Badge variant="secondary">{claim.tag}</Badge><h2 class="mt-4 font-heading text-3xl font-semibold">{claim.title}</h2><p class="mt-4 leading-7 text-muted-foreground">{claim.text}</p><p class="mt-5 text-xs text-muted-foreground">Source: {claim.source}</p></div></article>{/each}</div></section>
  <section class="bg-[#0b2546] py-16 text-white"><div class="mx-auto grid max-w-7xl gap-5 px-4 sm:px-6 md:grid-cols-3 lg:px-8"><Card class="border-white/15 bg-white/5 text-white shadow-none"><CardContent class="p-6"><strong class="font-heading text-2xl">Academic excellence</strong><p class="mt-2 text-sm leading-6 text-white/65">Healthy teaching and learning supported by appropriate infrastructure.</p></CardContent></Card><Card class="border-white/15 bg-white/5 text-white shadow-none"><CardContent class="p-6"><strong class="font-heading text-2xl">Ready for work</strong><p class="mt-2 text-sm leading-6 text-white/65">Contemporary knowledge and skills connected to employability.</p></CardContent></Card><Card class="border-white/15 bg-white/5 text-white shadow-none"><CardContent class="p-6"><strong class="font-heading text-2xl">Responsible practice</strong><p class="mt-2 text-sm leading-6 text-white/65">Social, ethical and professional responsibility across disciplines.</p></CardContent></Card></div></section>
</main></PublicShell>
