<script lang="ts">
 import PublicShell from "$public/components/PublicShell.svelte"; import PageHeader from "$public/components/PageHeader.svelte"; import { Button } from "$lib/components/ui/button"; import { Card, CardContent } from "$lib/components/ui/card"; import * as Tabs from "$lib/components/ui/tabs"; import * as Empty from "$lib/components/ui/empty"; import IconCalendar from "@tabler/icons-svelte/icons/calendar"; import IconFileDescription from "@tabler/icons-svelte/icons/file-description"; import IconCalendarTime from "@tabler/icons-svelte/icons/calendar-time"; import IconLock from "@tabler/icons-svelte/icons/lock";
</script>
<svelte:head><title>Academics · BBDIT</title></svelte:head>
<PublicShell><main><PageHeader eyebrow="Academics" title="Public academic information and student services" description="Find published syllabus, timetable and calendar information here. Personal schedules, attendance, leave and requests remain inside the secure campus app." />
  <section class="mx-auto max-w-7xl px-[clamp(1rem,4vw,2rem)] py-[clamp(3rem,8vw,4rem)]"><Tabs.Root value="syllabus"><Tabs.List class="mb-8 grid h-auto w-full grid-cols-1 gap-2 rounded-xl bg-muted p-2 min-[390px]:grid-cols-2 lg:grid-cols-4"><Tabs.Trigger value="syllabus" class="h-14 min-w-0 gap-2 rounded-lg px-2 text-sm sm:px-4 sm:text-base"><IconFileDescription class="size-5" />Syllabus</Tabs.Trigger><Tabs.Trigger value="timetable" class="h-14 min-w-0 gap-2 rounded-lg px-2 text-sm sm:px-4 sm:text-base"><IconCalendarTime class="size-5" />Timetable</Tabs.Trigger><Tabs.Trigger value="calendar" class="h-14 min-w-0 gap-2 rounded-lg px-2 text-sm sm:px-4 sm:text-base"><IconCalendar class="size-5" />College calendar</Tabs.Trigger><Tabs.Trigger value="private" class="h-14 min-w-0 gap-2 rounded-lg px-2 text-sm sm:px-4 sm:text-base"><IconLock class="size-5" />Private services</Tabs.Trigger></Tabs.List>
    <Tabs.Content value="syllabus"><div class="grid gap-5 md:grid-cols-2"><Card class="shadow-none"><CardContent class="p-6"><IconFileDescription class="size-7 text-primary" /><h2 class="mt-4 font-heading text-2xl font-semibold">AKTU syllabus</h2><p class="mt-2 text-sm leading-6 text-muted-foreground">Official curriculum and scheme information for AKTU-affiliated engineering, management and pharmacy programmes.</p><Button href="https://aktu.ac.in/syllabus.html" target="_blank" rel="noreferrer" class="mt-5">Open AKTU syllabus</Button></CardContent></Card><Card class="shadow-none"><CardContent class="p-6"><IconFileDescription class="size-7 text-primary" /><h2 class="mt-4 font-heading text-2xl font-semibold">Programme list</h2><p class="mt-2 text-sm leading-6 text-muted-foreground">Review every course and specialisation currently published by BBDIT.</p><Button href="/public/courses" variant="outline" class="mt-5">Browse courses</Button></CardContent></Card></div></Tabs.Content>
    <Tabs.Content value="timetable"><Empty.Root class="rounded-xl border border-dashed"><Empty.Header><Empty.Media variant="icon"><IconCalendarTime /></Empty.Media><Empty.Title>No public timetable is currently published</Empty.Title><Empty.Description>Students can view their section-specific timetable in the campus app.</Empty.Description></Empty.Header><Empty.Content><Button>Open campus app</Button></Empty.Content></Empty.Root></Tabs.Content>
    <Tabs.Content value="calendar"><Empty.Root class="rounded-xl border border-dashed"><Empty.Header><Empty.Media variant="icon"><IconCalendar /></Empty.Media><Empty.Title>No college calendar is currently published</Empty.Title><Empty.Description>The public academic-calendar source does not currently contain a downloadable calendar.</Empty.Description></Empty.Header></Empty.Root></Tabs.Content>
    <Tabs.Content value="private"><Empty.Root class="rounded-xl border border-dashed"><Empty.Header><Empty.Media variant="icon"><IconLock /></Empty.Media><Empty.Title>Sign in for personal academic services</Empty.Title><Empty.Description>Access attendance, your class schedule, leave applications, examination records and related enquiries securely.</Empty.Description></Empty.Header><Empty.Content><Button>Log in to campus app</Button></Empty.Content></Empty.Root></Tabs.Content>
  </Tabs.Root></section>
</main></PublicShell>
