<script lang="ts">
  import { onMount } from "svelte"; import PublicShell from "$public/components/PublicShell.svelte"; import PageHeader from "$public/components/PageHeader.svelte"; import { Badge } from "$lib/components/ui/badge"; import { Button } from "$lib/components/ui/button"; import { Card, CardContent } from "$lib/components/ui/card"; import * as Carousel from "$lib/components/ui/carousel"; import type { CarouselAPI } from "$lib/components/ui/carousel/context"; import convocation from "@/assets/bbdit-convocation.jpg";
  import agarwal from "@/assets/recruiter-agarwal.jpg"; import amul from "@/assets/recruiter-amul.jpg"; import apollo from "@/assets/recruiter-apollo.jpg"; import asian from "@/assets/recruiter-asian.jpg"; import bajaj from "@/assets/recruiter-bajaj.jpg"; import berger from "@/assets/recruiter-berger.jpg"; import bluedart from "@/assets/recruiter-bluedart.jpg"; import bridgestone from "@/assets/recruiter-bridgestone.jpg"; import british from "@/assets/recruiter-british.jpg"; import ceasefire from "@/assets/recruiter-ceasefire.jpg"; import coldex from "@/assets/recruiter-coldex.jpg"; import hdfc from "@/assets/recruiter-hdfc.jpg"; import indiamart from "@/assets/recruiter-indiamart.jpg"; import motherson from "@/assets/recruiter-motherson.jpg"; import nestle from "@/assets/recruiter-nestle.jpg"; import om from "@/assets/recruiter-om.jpg"; import radio from "@/assets/recruiter-radio.jpg"; import rak from "@/assets/recruiter-rak.jpg"; import spicejet from "@/assets/recruiter-spicejet.jpg"; import titan from "@/assets/recruiter-titan.jpg";
  const process=[["Prepare","Aptitude, communication, technical workshops and career mentoring."],["Connect","Industry visits, guest sessions, recruiter interaction and placement notices."],["Progress","Interview opportunities, alumni relationships and continued professional growth."]];
  const recruiters=[["Agarwal Packers",agarwal],["Amul",amul],["Apollo",apollo],["Asian Paints",asian],["Bajaj",bajaj],["Berger Paints",berger],["Blue Dart",bluedart],["Bridgestone",bridgestone],["British Paints",british],["Ceasefire",ceasefire],["ColdEX",coldex],["HDFC",hdfc],["IndiaMART",indiamart],["Motherson Sumi",motherson],["Nestlé",nestle],["OM Logistics",om],["Radio Mantra",radio],["RAK Ceramics",rak],["SpiceJet",spicejet],["Titan",titan]] as const;
  let recruiterCarousel: CarouselAPI | undefined; let carouselPaused=false;
  onMount(()=>{if(window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const timer=window.setInterval(()=>{if(!carouselPaused)recruiterCarousel?.scrollNext()},3000);return()=>window.clearInterval(timer)});
</script>
<svelte:head><title>Placements & Alumni · BBDIT</title></svelte:head>
<PublicShell><main><PageHeader eyebrow="Placements & alumni" title="From classroom learning to professional confidence" description="Career preparation, current placement activity and an alumni community connected by shared experience." />
  <section class="mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 lg:grid-cols-2 lg:items-center lg:px-8"><div><Badge>Training & placement</Badge><h2 class="mt-4 font-heading text-3xl font-semibold">Preparation is a continuous process</h2><p class="mt-4 leading-7 text-muted-foreground">BBDIT’s published placement activity includes recruiter drives, interview shortlists, workshops and career-building support. This page separates ongoing services from historic awards and avoids presenting old survey results as current rankings.</p><div class="mt-8 space-y-5">{#each process as item}<div class="border-l-2 border-primary pl-4"><h3 class="font-semibold">{item[0]}</h3><p class="mt-1 text-sm text-muted-foreground">{item[1]}</p></div>{/each}</div></div><img src={convocation} alt="BBDIT alumni at convocation" class="aspect-[4/3] w-full rounded-xl object-cover" /></section>
  <section class="border-y bg-muted/40"><div class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div class="flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-widest text-primary">Alumni</p><h2 class="mt-2 font-heading text-3xl font-semibold">Stay part of the BBDIT community</h2></div><Button>Join the alumni directory</Button></div><div class="mt-8 grid gap-4 md:grid-cols-3"><Card class="shadow-none"><CardContent class="p-6"><h3 class="font-heading text-xl font-semibold">Reconnect</h3><p class="mt-2 text-sm leading-6 text-muted-foreground">Find alumni events, reunions and opportunities to reconnect with classmates.</p></CardContent></Card><Card class="shadow-none"><CardContent class="p-6"><h3 class="font-heading text-xl font-semibold">Contribute</h3><p class="mt-2 text-sm leading-6 text-muted-foreground">Share professional experience through mentoring, talks and industry connections.</p></CardContent></Card><Card class="shadow-none"><CardContent class="p-6"><h3 class="font-heading text-xl font-semibold">Celebrate</h3><p class="mt-2 text-sm leading-6 text-muted-foreground">Document alumni journeys and milestones that can guide current students.</p></CardContent></Card></div></div></section>
  <section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><h2 class="font-heading text-3xl font-semibold">Placement desk</h2><div class="mt-7 grid gap-4 md:grid-cols-2"><Card class="shadow-none"><CardContent class="p-6"><Badge variant="secondary">Notice · 15 Jan 2026</Badge><h3 class="mt-4 font-semibold">Motherson Sumi interview shortlist</h3><p class="mt-2 text-sm text-muted-foreground">Students shortlisted for the face-to-face interview process.</p></CardContent></Card><Card class="shadow-none"><CardContent class="p-6"><Badge variant="secondary">Drive · 10 Dec 2025</Badge><h3 class="mt-4 font-semibold">HCL pool campus drive</h3><p class="mt-2 text-sm text-muted-foreground">Published opportunity for colleges in the Delhi NCR region.</p></CardContent></Card></div></section>
  <section class="border-t bg-muted/40"><div class="mx-auto max-w-7xl px-12 py-16 sm:px-16 lg:px-20"><p class="text-xs font-bold uppercase tracking-widest text-primary">Industry connections</p><h2 class="mt-2 font-heading text-3xl font-semibold">Companies that have recruited from BBDIT</h2><p class="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Official recruiter marks published in BBDIT’s admission material. The carousel pauses while you interact with it.</p><Carousel.Root setApi={(api)=>recruiterCarousel=api} opts={{ align: "start", loop: true }} class="mt-8 w-full" onmouseenter={()=>carouselPaused=true} onmouseleave={()=>carouselPaused=false} onfocusin={()=>carouselPaused=true} onfocusout={()=>carouselPaused=false}><Carousel.Content class="-ml-4">{#each recruiters as company}<Carousel.Item class="basis-full pl-4 sm:basis-1/2 lg:basis-1/4"><Card class="overflow-hidden border-border/80 bg-card shadow-none"><CardContent class="p-3"><div class="flex h-28 items-center justify-center rounded-lg border border-black/10 bg-white p-5 dark:border-white/15"><img src={company[1]} alt={`${company[0]} logo`} class="max-h-18 w-auto max-w-full object-contain" loading="lazy" /></div><p class="sr-only">{company[0]}</p></CardContent></Card></Carousel.Item>{/each}</Carousel.Content><Carousel.Previous /><Carousel.Next /></Carousel.Root></div></section>
</main></PublicShell>
